/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;

/**
 *
 * @author drean
 */
public class Resultados extends javax.swing.JFrame {

    /**
     * Creates new form Resultados
     */
    private final String nombre;
    private final String perfil;
    private final Map<String, String> consejos;
    private final Map<String, String> nombres;
    private final String[] lugar = {"trabajo equipo", "adaptacion", "miedo fracaso"};
    
    public Resultados(String nombre, String perfil, Map<String, String> consejos, Map<String, String> nombres) {
        this.nombre = nombre;
        this.perfil = perfil;
        this.consejos = consejos;
        this.nombres = nombres;
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        txtSubtitulo = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnPesos = new javax.swing.JLabel();
        btnConsejos = new javax.swing.JLabel();
        btnComparacion = new javax.swing.JLabel();
        sPesos = new javax.swing.JSeparator();
        sConsejos = new javax.swing.JSeparator();
        sComparacion = new javax.swing.JSeparator();
        main = new javax.swing.JPanel();
        pComparacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRte = new javax.swing.JLabel();
        txtRadap = new javax.swing.JLabel();
        txtRmf = new javax.swing.JLabel();
        txtRrf = new javax.swing.JLabel();
        pPesos = new javax.swing.JPanel();
        pConsejos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCte = new javax.swing.JLabel();
        txtCadap = new javax.swing.JLabel();
        txtCmf = new javax.swing.JLabel();
        txtRrf1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsejoFinal = new javax.swing.JTextArea();
        btnFinalizar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnComenzar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(70, 136, 240));

        txtTitulo.setFont(new java.awt.Font("Roboto Cn", 0, 33)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setText("Resultados");

        txtSubtitulo.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        txtSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtSubtitulo.setText("Los resultados son a base del perfil");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubtitulo)
                    .addComponent(txtTitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubtitulo)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        home.setBackground(new java.awt.Color(238, 238, 238));

        jPanel4.setBackground(new java.awt.Color(0, 188, 212));

        btnPesos.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        btnPesos.setForeground(new java.awt.Color(255, 255, 255));
        btnPesos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPesos.setText("Pesos");
        btnPesos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesosMouseClicked(evt);
            }
        });

        btnConsejos.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        btnConsejos.setForeground(new java.awt.Color(255, 255, 255));
        btnConsejos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConsejos.setText("Consejos");
        btnConsejos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsejos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsejosMouseClicked(evt);
            }
        });

        btnComparacion.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        btnComparacion.setForeground(new java.awt.Color(255, 255, 255));
        btnComparacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnComparacion.setText("Comparación");
        btnComparacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComparacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComparacionMouseClicked(evt);
            }
        });

        sPesos.setBackground(new java.awt.Color(255, 255, 141));

        sConsejos.setBackground(new java.awt.Color(255, 255, 141));

        sComparacion.setBackground(new java.awt.Color(255, 255, 141));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnComparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsejos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(256, 256, 256)
                    .addComponent(sPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(248, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addGap(0, 492, Short.MAX_VALUE)
                    .addComponent(sConsejos, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(sComparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 485, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsejos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(51, Short.MAX_VALUE)
                    .addComponent(sPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(51, Short.MAX_VALUE)
                    .addComponent(sConsejos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(51, Short.MAX_VALUE)
                    .addComponent(sComparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        main.setBackground(new java.awt.Color(250, 250, 250));
        main.setLayout(new java.awt.CardLayout());

        pComparacion.setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        jLabel1.setText("Trabajo en Equipo:");

        jLabel2.setText("Te entregamos los nombres de las personas con quien tienes cosas en comun.");

        jLabel6.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        jLabel6.setText("Adaptación:");

        jLabel7.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        jLabel7.setText("Miedo al fracaso:");

        jLabel8.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        jLabel8.setText("Rendirse con facilidad:");

        txtRte.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        txtRte.setText("Ninguno.");

        txtRadap.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        txtRadap.setText("Ninguno.");

        txtRmf.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        txtRmf.setText("Ninguno.");

        txtRrf.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        txtRrf.setText("Ninguno.");

        javax.swing.GroupLayout pComparacionLayout = new javax.swing.GroupLayout(pComparacion);
        pComparacion.setLayout(pComparacionLayout);
        pComparacionLayout.setHorizontalGroup(
            pComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pComparacionLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(pComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pComparacionLayout.createSequentialGroup()
                        .addGroup(pComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(24, 24, 24)
                        .addGroup(pComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRrf)
                            .addComponent(txtRmf)
                            .addComponent(txtRadap)
                            .addComponent(txtRte))))
                .addGap(0, 221, Short.MAX_VALUE))
        );
        pComparacionLayout.setVerticalGroup(
            pComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pComparacionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(pComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRadap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtRmf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRrf))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        main.add(pComparacion, "card4");

        pPesos.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout pPesosLayout = new javax.swing.GroupLayout(pPesos);
        pPesos.setLayout(pPesosLayout);
        pPesosLayout.setHorizontalGroup(
            pPesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        pPesosLayout.setVerticalGroup(
            pPesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        main.add(pPesos, "card3");

        pConsejos.setBackground(new java.awt.Color(250, 250, 250));

        jLabel9.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        jLabel9.setText("Rendirse con facilidad:");

        jLabel10.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        jLabel10.setText("Miedo al fracaso:");

        jLabel11.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        jLabel11.setText("Adaptación:");

        jLabel12.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        jLabel12.setText("Trabajo en Equipo:");

        jLabel13.setText("Si estas bien en algun aspecto, tu ya estas bien aconsejado.");

        txtCte.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        txtCte.setText("Ninguno.");

        txtCadap.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        txtCadap.setText("Ninguno.");

        txtCmf.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        txtCmf.setText("Ninguno.");

        txtRrf1.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        txtRrf1.setText("Ninguno.");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        txtConsejoFinal.setEditable(false);
        txtConsejoFinal.setColumns(20);
        txtConsejoFinal.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        txtConsejoFinal.setRows(5);
        txtConsejoFinal.setBorder(null);
        jScrollPane1.setViewportView(txtConsejoFinal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pConsejosLayout = new javax.swing.GroupLayout(pConsejos);
        pConsejos.setLayout(pConsejosLayout);
        pConsejosLayout.setHorizontalGroup(
            pConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsejosLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(pConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(pConsejosLayout.createSequentialGroup()
                        .addGroup(pConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(24, 24, 24)
                        .addGroup(pConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRrf1)
                            .addComponent(txtCmf)
                            .addComponent(txtCadap)
                            .addComponent(txtCte)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 76, Short.MAX_VALUE))
        );
        pConsejosLayout.setVerticalGroup(
            pConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsejosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(pConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCadap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCmf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pConsejosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtRrf1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        main.add(pConsejos, "card2");

        btnFinalizar.setBackground(new java.awt.Color(0, 150, 136));
        btnFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Cn", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FINALIZAR");

        javax.swing.GroupLayout btnFinalizarLayout = new javax.swing.GroupLayout(btnFinalizar);
        btnFinalizar.setLayout(btnFinalizarLayout);
        btnFinalizarLayout.setHorizontalGroup(
            btnFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFinalizarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        btnFinalizarLayout.setVerticalGroup(
            btnFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnFinalizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        btnComenzar.setBackground(new java.awt.Color(0, 150, 136));
        btnComenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComenzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComenzarMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Roboto Cn", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("COMENZAR");

        javax.swing.GroupLayout btnComenzarLayout = new javax.swing.GroupLayout(btnComenzar);
        btnComenzar.setLayout(btnComenzarLayout);
        btnComenzarLayout.setHorizontalGroup(
            btnComenzarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnComenzarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel15)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        btnComenzarLayout.setVerticalGroup(
            btnComenzarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnComenzarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 72, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnFinalizarMouseClicked

    private void btnComparacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComparacionMouseClicked
        pestanas(sComparacion, sConsejos, sPesos);
        paneles(pComparacion, pPesos, pConsejos);
    }//GEN-LAST:event_btnComparacionMouseClicked

    private void btnPesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesosMouseClicked
        pestanas(sPesos, sConsejos, sComparacion);
        paneles(pPesos, pComparacion, pConsejos);
    }//GEN-LAST:event_btnPesosMouseClicked

    private void btnConsejosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsejosMouseClicked
        pestanas(sConsejos, sPesos, sComparacion);
        paneles(pConsejos, pComparacion, pPesos);
    }//GEN-LAST:event_btnConsejosMouseClicked

    private void btnComenzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComenzarMouseClicked
        Main m = new Main();
        this.dispose();
        m.show();
    }//GEN-LAST:event_btnComenzarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultados("","", null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnComenzar;
    private javax.swing.JLabel btnComparacion;
    private javax.swing.JLabel btnConsejos;
    private javax.swing.JPanel btnFinalizar;
    private javax.swing.JPanel btnFinalizar1;
    private javax.swing.JLabel btnPesos;
    private javax.swing.JPanel btnSiguiente;
    private javax.swing.JPanel btnSiguiente1;
    private javax.swing.JPanel header;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pComparacion;
    private javax.swing.JPanel pConsejos;
    private javax.swing.JPanel pPesos;
    private javax.swing.JSeparator sComparacion;
    private javax.swing.JSeparator sConsejos;
    private javax.swing.JSeparator sPesos;
    private javax.swing.JLabel txtCadap;
    private javax.swing.JLabel txtCmf;
    private javax.swing.JTextArea txtConsejoFinal;
    private javax.swing.JLabel txtCte;
    private javax.swing.JLabel txtRadap;
    private javax.swing.JLabel txtRmf;
    private javax.swing.JLabel txtRrf;
    private javax.swing.JLabel txtRrf1;
    private javax.swing.JLabel txtRte;
    private javax.swing.JLabel txtSubtitulo;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables

    private void inicializar(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txtTitulo.setText(txtTitulo.getText() + " de " + nombre);
        txtSubtitulo.setText(txtSubtitulo.getText() + " " + perfil);
        txtConsejoFinal.setText("Como consejo final, solo queremos decirte que nadie es perfecto \n" +
                "y que todos podemos mejorar, asi que a esforzarse se ha dicho. \n" +
                "¡Grandes logros te esperan!");
        pestanas(sComparacion, sConsejos, sPesos);
        reemplazar();
    }
    
    private void reemplazar(){
        for(Map.Entry<String, String> entry: nombres.entrySet()){
            if(!entry.getValue().equals("")){
                if(lugar[0].equals(entry.getKey())){txtRte.setText(entry.getValue());}
                else if(lugar[1].equals(entry.getKey())){txtRadap.setText(entry.getValue());}
                else if(lugar[2].equals(entry.getKey())){txtRmf.setText(entry.getValue());}
            }else{
                System.out.println("Nombre vacio: " + entry.getKey());
            }
        }
        for(Map.Entry<String, String> entry: consejos.entrySet()){
            if(!entry.getValue().equals("")){
                if(lugar[0].equals(entry.getKey())){txtCte.setText(entry.getValue());}
                else if(lugar[1].equals(entry.getKey())){txtCadap.setText(entry.getValue());}
                else if(lugar[2].equals(entry.getKey())){txtCmf.setText(entry.getValue());}
            }else{
                System.out.println("Consejo vacio: " + entry.getKey());
            }
        }
    }
    
    private void pestanas(JSeparator activo, JSeparator inactivo, JSeparator inac){
        activo.setVisible(true);
        inactivo.setVisible(false);
        inac.setVisible(false);        
    }
    
    private void paneles(JPanel activo, JPanel inactivo, JPanel inac){
        activo.setVisible(true);
        inactivo.setVisible(false);
        inac.setVisible(false);
    }

}
